name: Upload release docker image

on:
  release:
    types: [ published ]

concurrency:
  group: holoinsight-agent-upload-release-docker-image
  cancel-in-progress: true

jobs:
  upload-release-docker-image:
    runs-on: ubuntu-latest
    steps:
    - name: run
      shell: bash
      run: |
        echo ok
